version: "3.9"  # optional since v1.27.0

services:
  postgresql:
    container_name: postgresql-db
    image: postgres:14.1
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  pgadmin:
    container_name: postgresql-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


volumes:
  postgresdata:
    external: true